[project]
name = "gh-mcp"
version = "0.1.0"
description = "Refined MCP server for GitHub GraphQL API"
requires-python = ">=3.12"
dependencies = [
    "fastmcp~=2.12.5",
]
scripts = { gh-mcp = "gh_mcp.__main__:main" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "file"
path = "impl.py"
