[project]
name = "gh-mcp"
dynamic = ["version"]
readme = "README.md"
description = "Refined MCP server for GitHub GraphQL API"
requires-python = ">=3.12"
dependencies = [
    "fastmcp~=2.12.5",
]
scripts = { gh-mcp = "gh_mcp.__main__:main" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.version]
source = "file"
path = "gh_mcp/impl.py"

[tool.pdm.build]
includes = ["gh_mcp"]
