version: 2

updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: uv
    directory: /packages/gh
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
